export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  APP_ROOT: "/app",
  DASHBOARD: "/app/dashboard",
  TEAMS: "/app/teams",
  TEAM_DETAIL: (teamId) => `/app/teams/${teamId}`,
  PROJECTS: "/app/projects",
  PROJECT_DETAIL: (projectId) => `/app/projects/${projectId}`,
  TASKS: "/app/tasks",
  ASSIGNMENTS: "/app/assignments",
  NOTIFICATIONS: "/app/notifications",
  ADMIN: "/app/admin",
  REGISTER: "/app/register",
  FORBIDDEN: "/forbidden",
}
