export const TASK_STATUSES = Object.freeze({
  TODO: "TODO",
  IN_PROGRESS: "IN_PROGRESS",
  REVIEW: "REVIEW",
  COMPLETED: "COMPLETED",
})

export const TASK_STATUS_ORDER = [
  TASK_STATUSES.TODO,
  TASK_STATUSES.IN_PROGRESS,
  TASK_STATUSES.REVIEW,
  TASK_STATUSES.COMPLETED,
]

export const TASK_STATUS_LABELS = {
  [TASK_STATUSES.TODO]: "To do",
  [TASK_STATUSES.IN_PROGRESS]: "In progress",
  [TASK_STATUSES.REVIEW]: "In review",
  [TASK_STATUSES.COMPLETED]: "Completed",
}

export const TASK_STATUS_FILTER_ALL = "ALL"
